### ISSUE TITLE
Soft-links unusable on Windows

### ISSUE THREAD

**Issue by kmpeters** [EPICS-synApps/configure#3]
When the configure repo is cloned on Windows the soft-links for the EPICS.<arch> and SUPPORT.<arch> files are converted into text files containing the name of the linked file.  The existence of these files breaks Windows builds for users who prefer the single-RELEASE-file approach.  It also makes it more complicated to use one of the soft-linked architecture files; instead of simply editing the file the user has to (1) realize the file contents are completely incorrect, (2) find the file for the arch that has the valid content, (3) copy the valid content and (4) edit the content.

A better approach would be to prefix all of the EPICS_BASE.<arch> and SUPPORT.<arch> files with "EXAMPLE_", like areaDetector does with its RELEASE files.  The soft-links would could then be replaced with valid examples, which wouldn't break Windows builds by default.

**Comment by MarkRivers** [comment]
I am the one that added those soft link files.  They work for me on Windows because I actually build for Windows on a Linux file system.  The EPICS_BASE.win32-x86 and SUPPORT.win32-x86 are real files, and all of the other ones (windows-x64, etc.) are soft links.  You could just delete all of the soft link files and add some documentation explaining that soft links are convenient to use if they are supported.  When building for multiple Windows architectures and soft links are supported then only 1 file needs to be edited when changing to a new version of base, rather than 8 files.

**Comment by kmpeters** [comment]
I like the approach taken by areaDetector, using the EXAMPLE_ prefix to the EPICS_BASE.<arch> and SUPPORT.<arch> files.  People who don't need it can ignore them and nothing is broken.  Those who do need them can copy or sym-link the necessary files.
